project:
  type: website

website:
  navbar:
    title: false
    collapse-below: sm
    left:
      - icon: house-door
        href: https://tsostarics.com/
    right:
      - text: ABOUT
        href: https://www.tsostarics.com/about/
      - text: POSTS
        href: https://tsostaricsblog.netlify.app
      - text: RESEARCH
        href: https://www.tsostarics.com/research/
  comments:
    utterances:
      repo: tsostarics/blog
      theme: github-light
      issue-term: title
  page-footer:
    center:
      - icon: github
        href: https://github.com/tsostarics/
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/t_sostarics
        aria-label: Twitter
    right:
      - text: "Contact"
        href: https://www.tsostarics.com/contact/
format:
  html:
    theme:
      light: hex-light.scss
      dark: hex-dark.scss
    css: styles.css


